#!/usr/bin/perl

($name, $cmd, $cores, $extra_flags) =  @ARGV;

$cores=1 unless $cores;



open O, ">mymsub_tmpfile";
print O "#!/bin/sh\n";

if ($extra_flags =~ /--timeout=(\d+)/) {
    my $timestr = sprintf "%2d:%2d:%2d",
                 int($1/(60*60)),
                 int( ($1/60)%60),
                 int( $1%(60));
    $timestr =~ s/\s/0/g;

    print O "#PBS -l walltime=$timestr\n";
    $extra_flags =~ s/--timeout=(\d+)//;
}

print O "time $cmd\n";
close O;

my $cwd = `pwd`;
chomp $cwd;


$cmd = qq[msub mymsub_tmpfile -V -N $name -d $cwd $extra_flags -l nodes=1:ppn=$cores];
print "$cmd\n";
`$cmd`;

unlink mymsub_tmpfile
