#! /usr/bin/perl 

# Do a piece of a rmark benchmark, for Exonerate.
#
# This script is normally called by rmark-master.pl; its command line
# syntax is tied to rmark-master.pl.
# x-exonerate doesn't use <modeldir>, but it's passed in so that
# rmark-master.pl can use a consistent command line structure for
# all search programs (cmsearch uses it, for example).
#
# Usage:      x-exonerate <execdir>               <scriptdir> <modeldir> <resultdir> <optsfile>       <tblfile> <msafile>  <posfile>  <fafile> <outfile>
# Example:  ./x-exonerate /usr/local/blast/bin/   ../rmark/   models    testdir     exonerate.opts test.tbl  rmark3.msa rmark3.pos test.fa  test.out
#
# Command-line options:
# -P     : run a positive-only benchmark, only each family's positive sequences will be searched
#
# SRE, Tue Apr 20 10:32:49 2010 [Janelia]
# SVN $Id$
#
use Getopt::Std;
use Time::HiRes;
getopts('P');
$do_posonly = 0;
if (defined $opt_P) { $do_posonly = 1; }

$usage = "Usage: $0 [options]\n\t<execdir>\n\t<scriptdir>\n\t<modeldir>\n\t<resultdir>\n\t<optsfile>\n\t<tblfile>\n\t<msafile>\n\t<posfile>\n\t<fafile>\n\t<outfile>\n";
$options_usage  = "Options:\n\t";
$options_usage .= " -P     : run a positive-only benchmark, only each family's positive sequences will be searched\n\t";
if(scalar(@ARGV) != 10) { printf("$usage\n$options_usage"); exit(1); }

($execdir, $scriptdir, $modeldir, $resultdir, $optsfile, $tblfile, $msafile, $posfile, $fafile, $outfile) = @ARGV;
$tmpoutfile = $outfile . ".tmp";
$sorttmpoutfile = $outfile . ".tmp.sort";

$idscript   = "$scriptdir/rmark-idpositives.pl";
$exonerat   = "$execdir/exonerate";
$afetch     = "$execdir/esl-afetch";
$sfetch     = "$execdir/esl-sfetch";
$reformat   = "$execdir/esl-reformat";
if(! -e $afetch) { 
    $afetch     = "$execdir/../easel/miniapps/esl-afetch";
    if(! -e $afetch) { die "$afetch does not exist, nor $execdir/$afetch"; }
}
if(! -e $sfetch) { 
    $sfetch     = "$execdir/../easel/miniapps/esl-sfetch";
    if(! -e $sfetch) { die "$sfetch does not exist, nor $execdir/$sfetch"; }
}
if(! -e $reformat) { 
    $reformat = "$execdir/../easel/miniapps/esl-reformat";
    if(! -e $reformat) { die "$reformat does not exist"; }
}    
if(! -e $exonerate) { 
    $exonerate = "/home/um/wshands/Exonerate/exonerate-2.2.0-x86_64/bin/exonerate";

    if(! -e $exonerate) { die "$exonerate does not exist"; }
}    

if (! -d $execdir)                                      { die "didn't find executable directory $execdir"; }
if (! -d $scriptdir)                                    { die "didn't find script directory $scriptdir"; }
if (! -e $resultdir)                                    { die "$resultdir doesn't exist"; }
if (! -e $posfile)                                      { die "$posfile doesn't exist"; }
if (! -e $idscript)                                     { die "positive identification script $idscript doesn't exist"; }
if (! -e $optsfile)                                     { die "options file $optsfile doesn't exist"; }

# read options file
open(OPTS, $optsfile) || die "couldn't open options file $optsfile"; 
$searchopts = <OPTS>;
close(OPTS);
chomp $searchopts;

open(OUTFILE,">$outfile") || die "failed to open $outfile";
open(TMPOUTFILE,">$tmpoutfile") || die "failed to open $tmpoutfile";
open(TABLE, "$tblfile")   || die "failed to open $tblfile";
$orig_fafile = $fafile;
while (<TABLE>)
{
    $runtime = -1 * Time::HiRes::time();

    ($msaname) = split;

    # fetch the msa
    $command = "$afetch -o $resultdir/$msaname.sto $msafile $msaname > /dev/null";
    $status = system("$command");
    if ($status != 0) { die "FAILED: $command"; }

    # generate the query fasta file
    $command = "$reformat fasta $resultdir/$msaname.sto > $resultdir/$msaname.query";
    $status = system("$command");
    if ($status != 0) { die "FAILED: $command"; }

    # run exonerate
    $command = "$exonerate $searchopts --querytype protein --targettype dna --model protein2dna  --query $resultdir/$msaname.query --target $fafile --showalignment no --showsugar true --showvulgar no > $resultdir/$msaname.tmp";
 
    $status = system("$command");
    if ($status != 0) { die "FAILED: $command"; }

    open(OUTPUT, "$resultdir/$msaname.tmp") || die "FAILED: to open $resultdir/$msaname.tmp tabular output file"; 

    while (<OUTPUT>)
    {
	if (!/^sugar/) { next; }
	@fields   = split(' ', $_, 12);
	$target      = $fields[5];
	$target_from = $fields[6];
	$target_to   = $fields[7];
	$bitscore    = $fields[9];
	printf TMPOUTFILE "%10g %10.1f %10d %10d %20s %35s\n", $bitscore, $bitscore, $target_from, $target_to, $target, $msaname;
    }

    #unlink "$resultdir/$msaname.tmp";
    unlink "$resultdir/$msaname.sto";
    unlink "$resultdir/$msaname.query";

    $runtime += Time::HiRes::time();
    open(TIME, ">" . "$resultdir/$msaname.time");
    printf TIME ("$msaname %.2f seconds\n", $runtime);    
    close(TIME);
}
close TABLE;
close OUTFILE;
close TMPOUTFILE;

# Use 'rmark-idpositives.pl' to identify positives in the temporary output file to
# create the permanent output file. First, we need to sort by score.

$command = "sort -rg $tmpoutfile > $sorttmpoutfile";
$status = system("$command");
if ($status != 0) { die "FAILED: $command"; }

$command = "perl $idscript $posfile $sorttmpoutfile > $outfile";
$status = system("$command");
if ($status != 0) { die "FAILED: $command"; }

$orfoutfile = $outfile . ".orf";
$orfposfile = $posfile . ".orf";
#printf("ORF pos file is %s\n",$orfposfile);
if( -e $orfposfile) {
#  printf("getting ORF pos file %s\n",$orfposfile);     
  $command = "perl $idscript $orfposfile $sorttmpoutfile > $orfoutfile";
  $status = system("$command");
  if ($status != 0) { die "FAILED: $command"; }
}
 
